server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_db
    username: root
    password: 1234

  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

  cache:
    type: redis
    redis:
#      time-to-live: 30000
      cache-null-values: true